=== yucren/QRCodePrintWebSite/xmlFiles/family.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"  targetNamespace="http://www.lonking.cn/family"  elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="family">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="person">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="age" type="xs:unsignedByte" />
              <xs:element name="birthday" type="xs:date" />
              <xs:element name="heigth" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== yucren/QRCodePrintWebSite/xmlFiles/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns="http://www.lonking.cn/family" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="family.xsd" >
  <person>
    <name>yuchengren</name>
    <age>30r</age>
    <birthday>1990-01-01</birthday>
    <heigth>173</heigth>
  </person>
  <person>
    <name>youmeixiang</name>
    <age>27</age>
    <birthday>1991-06-14</birthday>
    <heigth>155</heigth>
  </person>
  <person>
    <name>yujiaming</name>
    <age>4</age>
    <birthday>2014-03-20</birthday>
    <heigth>94</heigth>
  </person>
</family>
